# Generated by Django 4.0.4 on 2022-04-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'info',
                'managed': False,
            },
        ),
    ]
